version: 2

project_name: sse-contract-tests

builds:
- env:
  - CGO_ENABLED=0
  main: .
  binary: sse-contract-tests
  ldflags:
  - -s -w -X internal.version.Version={{.Version}}

  goos:
    - darwin
    - linux
    - windows
  ignore: # Go 1.15+ doesn't support 32-bit Darwin
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm64

release:
  disable: true # this disables releasing *to GitHub*;
  # (we want release-please to be responsible for doing all the GitHub release manipulations)

snapshot:
  # Allows you to change the version of the generated snapshot
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default is `{{ .Version }}-SNAPSHOT-{{.ShortCommit}}`.
  version_template: '{{ if index .Env "LD_RELEASE_VERSION"  }}{{ .Env.LD_RELEASE_VERSION }}{{ else }}0.0.0-SNAPSHOT{{ end }}'

archives:
  -
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

    # Configure the archive names so they'll be easy for an install script to get from GitHub.
    # For Linux & MacOS, we'll use the same OS and architecture strings that are returned by
    # "uname -s" and "uname -m". So, for instance, the amd64 Linux build will be called
    # "sse-contract-tests_Linux_x86_64.tar.gz".
    name_template: "{{ .ProjectName }}_{{ .Os | title }}_{{ .Arch | replace \"amd64\" \"x86_64\" | replace \"386\" \"i386\" }}"

    files:
      - LICENSE.txt
      - README.md
      - CHANGELOG.md
