version: 2.1

workflows:
  version: 2
  test:
    jobs:
    - docker-build-and-smoke-test

jobs:
  docker-build-and-smoke-test:
    docker:
      - image: ubuntu:20.04

    steps:
      - checkout

      - setup_remote_docker

      - run: docker build --tag sse-contract-tests .

      - run:
          command: while true ; do  echo -e "HTTP/1.1 500 Nope\n\n" | nc -l -p 8000  ; done
          background: true

      - run: (docker run -p 8111:8111 --url http://localhost:8000 2>&1 || true) | tee test.log

      - run: grep "test service returned status code 500" <test.log
