version: 2.1

workflows:
  version: 2
  test:
    jobs:
    - docker-build-and-smoke-test

jobs:
  docker-build-and-smoke-test:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker-smoke-test
